### PR TITLE
Change update algo to only change when needed

### PR DESCRIPTION
**Pull request by AbelLykens**
Get current policy (name + properties)
Compare to prospective (new) policy
If ANYTHING has changed (name or any property), only then do the chan update

Dry run is now outside of the chan update.

### CODE REVIEW

**Comment by accumulator** [comment]
The main issue I have with this is that you can't really reliably determine the current policy from LND and the policy configuration alone, for the following reasons:
1. charge-lnd config might have changed in between runs
2. user might have manually set fees between runs
3. some strategies result in dynamic fees, which makes them impossible to deterministically match against

So, without any persistence of the selected policies for each channel in previous runs, there's no certainty what the previous policy was. 

The code in `def current_policy()` also makes some assumptions that are incorrect.
1. Not all strategies define a `fee_ppm` config property (e.g. `strategy = cost`)
2. policies are only checked against the strategy config (base fee and ppm), which might match against the wrong policy if multiple policies use the same strategy. Also can't use the matching logic to get the correct policy, since the conditions for each channel might have changed in the meantime..

It would be doable however once there's a daemon mode (see #3), where we can store current policies in-memory as a list.

**Comment by AbelLykens** [comment]
Okay so then we have no real benefit now (apart from showing nice from->to names). We could store a backup config file every run, and use that to detect the old policy at new run?

**Comment by accumulator** [comment]
> Okay so then we have no real benefit now (apart from showing nice from->to names). We could store a backup config file every run, and use that to detect the old policy at new run?

A backup config file would still be problematic, due to (3). Only a file containing `chan.id,policy_name` tuples would work reliably, but then still the policy name would only be an aesthetic feature, since an unchanged policy could still result in different base_fee and fee_ppm outputs for that run.

I think the only functional use of policy name change detection is if it's used in a notification-like feature (e.g send email when policy changes for a channel)

**Comment by AbelLykens** [comment]
Well that is currently the reason I do it haha.
`./charge-lnd | mail -Es "Policy change" root`

**Comment by accumulator** [comment]
lol :-)

Not trying to be pedantic, but this is also sending emails if the policy name doesn't change, but the fees do ;-)

That said, implementing the storage of policy selection for previous runs is a small can of worms.. It changes charge-lnd from stateless to stateful. Where to store the state file? What if there's read errors. Write errors? Extra complexity if running from containers if you want to track this across instances etc.

There might also be another way to make this work without making charge-lnd stateful. 

If there's an option to output all channel policies (basically the old behaviour, but enabled through a CLI switch, e.g. --verbose) to a file, you can `diff` each run against the previous one

```
./charge-lnd --verbose |sort >/tmp/charge-lnd.log
diff /tmp/charge-lnd.log.1 /tmp/charge-lnd.log | mail -Es "Policy change" root
mv /tmp/charge-lnd.log /tmp/charge-lnd.log.1

```

**Comment by accumulator** [comment]
I have updated the branch without previous policy test, but any change in fees is now visible (implying policy change, or dynamic policy). What do you think?

**Comment by AbelLykens** [comment]
I see your points, but I think I will stay at my version, also detection changes from/to default for example ;). 
Detecting old now-changed policies will be problematic, true. Daemonizing would be interesting, also then not touching manually changed channels possibly [?]. Sounds like quite a reengineering task though.

**Comment by accumulator** [comment]
Ok, fair enough. I'll merge this PR as it is now, as I really like the conditional output only when a change is applied.
Thanks!

**Comment by AbelLykens** [comment]
:+1:

**Pull request merged**
